In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("daily-total-female-births.csv", header=0)

In [3]:
data.head()

         Date  Births
0  1959-01-01      35
1  1959-01-02      32
2  1959-01-03      30
3  1959-01-04      31
4  1959-01-05      44

In [4]:
data["Date"].dtype

In [5]:
data.shape

(365, 2)

In [6]:
data.describe()

           Births
count  365.000000
mean    41.980822
std      7.348257
min     23.000000
25%     37.000000
50%     42.000000
75%     46.000000
max     73.000000

In [7]:
data_with_date_type = pd.read_csv(
    "daily-total-female-births.csv", header=0, parse_dates=[0]
)

In [8]:
data_with_date_type.head()

        Date  Births
0 1959-01-01      35
1 1959-01-02      32
2 1959-01-03      30
3 1959-01-04      31
4 1959-01-05      44

In [9]:
data_with_date_type["Date"].dtype

dtype('<M8[us]')

In [10]:
data_with_date_type.shape

(365, 2)

In [11]:
data_with_date_type[
    (data_with_date_type["Date"] >= "1959-01-01")
    & (data_with_date_type["Date"] <= "1959-01-21")
]

         Date  Births
0  1959-01-01      35
1  1959-01-02      32
2  1959-01-03      30
3  1959-01-04      31
4  1959-01-05      44
5  1959-01-06      29
6  1959-01-07      45
7  1959-01-08      43
8  1959-01-09      38
9  1959-01-10      27
10 1959-01-11      38
11 1959-01-12      33
12 1959-01-13      55
13 1959-01-14      47
14 1959-01-15      45
15 1959-01-16      37
16 1959-01-17      50
17 1959-01-18      43
18 1959-01-19      41
19 1959-01-20      52
20 1959-01-21      34

In [12]:
data_with_date_type.describe()

                      Date      Births
count                  365  365.000000
mean   1959-07-02 00:00:00   41.980822
min    1959-01-01 00:00:00   23.000000
25%    1959-04-02 00:00:00   37.000000
50%    1959-07-02 00:00:00   42.000000
75%    1959-10-01 00:00:00   46.000000
max    1959-12-31 00:00:00   73.000000
std                    NaN    7.348257

In [13]:
feature = data_with_date_type.copy()
feature["Year"] = data_with_date_type["Date"].dt.year
feature["Month"] = data_with_date_type["Date"].dt.month
feature["Day"] = data_with_date_type["Date"].dt.day
feature.head()

        Date  Births  Year  Month  Day
0 1959-01-01      35  1959      1    1
1 1959-01-02      32  1959      1    2
2 1959-01-03      30  1959      1    3
3 1959-01-04      31  1959      1    4
4 1959-01-05      44  1959      1    5

In [14]:
feature["lag1"] = data_with_date_type["Births"].shift(1)
feature["lag2"] = data_with_date_type["Births"].shift(365)
feature.head()

        Date  Births  Year  Month  Day  lag1  lag2
0 1959-01-01      35  1959      1    1   NaN   NaN
1 1959-01-02      32  1959      1    2  35.0   NaN
2 1959-01-03      30  1959      1    3  32.0   NaN
3 1959-01-04      31  1959      1    4  30.0   NaN
4 1959-01-05      44  1959      1    5  31.0   NaN

In [15]:
feature["Roll_Mean"] = data_with_date_type["Births"].rolling(window=2).mean()
feature.head()

        Date  Births  Year  Month  Day  lag1  lag2  Roll_Mean
0 1959-01-01      35  1959      1    1   NaN   NaN        NaN
1 1959-01-02      32  1959      1    2  35.0   NaN       33.5
2 1959-01-03      30  1959      1    3  32.0   NaN       31.0
3 1959-01-04      31  1959      1    4  30.0   NaN       30.5
4 1959-01-05      44  1959      1    5  31.0   NaN       37.5

In [16]:
feature["Roll_Max"] = data_with_date_type["Births"].rolling(window=3).max()
feature.head()

        Date  Births  Year  Month  Day  lag1  lag2  Roll_Mean  Roll_Max
0 1959-01-01      35  1959      1    1   NaN   NaN        NaN       NaN
1 1959-01-02      32  1959      1    2  35.0   NaN       33.5       NaN
2 1959-01-03      30  1959      1    3  32.0   NaN       31.0      35.0
3 1959-01-04      31  1959      1    4  30.0   NaN       30.5      32.0
4 1959-01-05      44  1959      1    5  31.0   NaN       37.5      44.0

In [17]:
feature["Expand_Max"] = data_with_date_type["Births"].expanding().max()
feature.head()

,Date,Births,Year,Month,Day,lag1,lag2,Roll_Mean,Roll_Max,Expand_Max
0,1959-01-01,35,1959,1,1,NaN,NaN,NaN,NaN,35.0
1,1959-01-02,32,1959,1,2,35.0,NaN,33.5,NaN,35.0
2,1959-01-03,30,1959,1,3,32.0,NaN,31.0,35.0,35.0
3,1959-01-04,31,1959,1,4,30.0,NaN,30.5,32.0,35.0
4,1959-01-05,44,1959,1,5,31.0,NaN,37.5,44.0,44.0

In [18]:
data_as_series = pd.read_csv(
    "daily-total-female-births.csv",
    header=0,
    parse_dates=[0],
    index_col=0,
).squeeze("columns")

In [19]:
data_as_series.head()

Date
1959-01-01    35
1959-01-02    32
1959-01-03    30
1959-01-04    31
1959-01-05    44
Name: Births, dtype: int64

In [20]:
data_as_series.dtype

dtype('int64')

In [21]:
data_as_series["1959-01"]

Date
1959-01-01    35
1959-01-02    32
1959-01-03    30
1959-01-04    31
1959-01-05    44
1959-01-06    29
1959-01-07    45
1959-01-08    43
1959-01-09    38
1959-01-10    27
1959-01-11    38
1959-01-12    33
1959-01-13    55
1959-01-14    47
1959-01-15    45
1959-01-16    37
1959-01-17    50
1959-01-18    43
1959-01-19    41
1959-01-20    52
1959-01-21    34
1959-01-22    53
1959-01-23    39
1959-01-24    32
1959-01-25    37
1959-01-26    43
1959-01-27    39
1959-01-28    35
1959-01-29    44
1959-01-30    38
1959-01-31    24
Name: Births, dtype: int64

In [22]:
data_as_series.describe()

count    365.000000
mean      41.980822
std        7.348257
min       23.000000
25%       37.000000
50%       42.000000
75%       46.000000
max       73.000000
Name: Births, dtype: float64