In [ ]:
import pandas as pd

In [ ]:
employees_df = pd.read_csv('employees.csv')

In [ ]:
employees_df

   EmployeeID     Name   Department
0         101    Alice  Engineering
1         102      Bob        Sales
2         103  Charlie    Marketing
3         105      Eve  Engineering
4         106    Frank        Sales

In [ ]:
salary_df = pd.read_csv('salaries.csv')

In [ ]:
salary_df

   EmployeeID  Salary  Bonus
0         101   95000   5000
1         102   82000   3000
2         103   75000   2000
3         104   88000   4000
4         105   91000   4500

In [ ]:
merged_df = pd.merge(employees_df,salary_df,on='EmployeeID',how='left')

In [ ]:
merged_df

   EmployeeID     Name   Department   Salary   Bonus
0         101    Alice  Engineering  95000.0  5000.0
1         102      Bob        Sales  82000.0  3000.0
2         103  Charlie    Marketing  75000.0  2000.0
3         105      Eve  Engineering  91000.0  4500.0
4         106    Frank        Sales      NaN     NaN

In [ ]:
merged_df = pd.merge(employees_df,salary_df,on='EmployeeID',how='right')

In [ ]:
merged_df

   EmployeeID     Name   Department  Salary  Bonus
0         101    Alice  Engineering   95000   5000
1         102      Bob        Sales   82000   3000
2         103  Charlie    Marketing   75000   2000
3         104      NaN          NaN   88000   4000
4         105      Eve  Engineering   91000   4500

In [ ]:
merged_df = pd.merge(employees_df,salary_df,on='EmployeeID',how='outer',indicator=True)

In [ ]:
merged_df[merged_df['_merge']=='left_only']

   EmployeeID   Name Department  Salary  Bonus     _merge
5         106  Frank      Sales     NaN    NaN  left_only

In [ ]:
new_hire_df = pd.read_csv('new_hires.csv')

In [ ]:
new_hire_df

    Name Department  EmployeeID
0  Grace         HR         107
1  Henry    Finance         108
2    Ivy         IT         109

In [ ]:
pd.concat([employees_df,new_hire_df],ignore_index=True)

   EmployeeID     Name   Department
0         101    Alice  Engineering
1         102      Bob        Sales
2         103  Charlie    Marketing
3         105      Eve  Engineering
4         106    Frank        Sales
5         107    Grace           HR
6         108    Henry      Finance
7         109      Ivy           IT

In [ ]:
merged_df.pivot_table(values='Bonus', index='Name', columns='Department', aggfunc='mean',fill_value=0,margins=True)

Department  Engineering  Marketing   Sales     All
Name
Alice            5000.0        0.0     0.0  5000.0
Bob                 0.0        0.0  3000.0  3000.0
Charlie             0.0     2000.0     0.0  2000.0
Eve              4500.0        0.0     0.0  4500.0
All              4750.0     2000.0  3000.0  3625.0

In [ ]:
merged_df

   EmployeeID     Name   Department   Salary   Bonus      _merge
0         101    Alice  Engineering  95000.0  5000.0        both
1         102      Bob        Sales  82000.0  3000.0        both
2         103  Charlie    Marketing  75000.0  2000.0        both
3         104      NaN          NaN  88000.0  4000.0  right_only
4         105      Eve  Engineering  91000.0  4500.0        both
5         106    Frank        Sales      NaN     NaN   left_only

In [ ]:
salary_df

   EmployeeID  Salary  Bonus
0         101   95000   5000
1         102   82000   3000
2         103   75000   2000
3         104   88000   4000
4         105   91000   4500

In [ ]:
salary_df.sort_values(by='Salary', ascending=False)

   EmployeeID  Salary  Bonus
0         101   95000   5000
4         105   91000   4500
3         104   88000   4000
1         102   82000   3000
2         103   75000   2000