In [ ]:
import pandas as pd
import numpy as np

In [ ]:
pd.__version__

'2.3.3'

In [ ]:
df = pd.DataFrame(np.random.randn(10).reshape(2,5), columns=['A','B','C','D','E'])

In [ ]:
df

          A         B         C         D         E
0  1.585592  0.213530 -0.924150 -1.055195  0.197332
1  0.284527  0.551817 -0.751511 -0.801204  2.352792

In [ ]:
df['A']

0    1.585592
1    0.284527
Name: A, dtype: float64

In [ ]:
df[['A']]

          A
0  1.585592
1  0.284527

In [ ]:
df['B'] + df['D']

0   -0.841665
1   -0.249387
dtype: float64

In [ ]:
df = df.drop('C',axis=1)

In [ ]:
df

          A         B         D         E
0  1.585592  0.213530 -1.055195  0.197332
1  0.284527  0.551817 -0.801204  2.352792

In [ ]:
df['A']

0    1.585592
1    0.284527
Name: A, dtype: float64

In [ ]:
df.loc[1]

A    0.284527
B    0.551817
D   -0.801204
E    2.352792
Name: 1, dtype: float64

In [ ]:
df

          A         B         D         E
0  1.585592  0.213530 -1.055195  0.197332
1  0.284527  0.551817 -0.801204  2.352792

In [ ]:
df.index = ['P','Q']

In [ ]:
df

          A         B         D         E
P  1.585592  0.213530 -1.055195  0.197332
Q  0.284527  0.551817 -0.801204  2.352792

In [ ]:
df.loc['P']

A    1.585592
B    0.213530
D   -1.055195
E    0.197332
Name: P, dtype: float64

In [ ]:
df.iloc[1]

A    0.284527
B    0.551817
D   -0.801204
E    2.352792
Name: Q, dtype: float64

In [ ]:
ipl_df = pd.read_csv('data/IPL_Matches_2008_2022.csv')

In [ ]:
ipl_df.head()

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan

In [ ]:
ipl_df.describe(include='all')

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
count,9.500000e+02,899,950,950,950,950,950,950,950,950,946,946,950,932.000000,19,946,950,950,950,950
unique,NaN,33,706,15,80,18,18,49,18,2,2,18,4,NaN,1,262,932,937,58,60
top,NaN,Mumbai,2014-05-10,2013,Final,Royal Challengers Bangalore,Mumbai Indians,Eden Gardens,Mumbai Indians,field,N,Mumbai Indians,Wickets,NaN,D/L,AB de Villiers,"['RD Gaikwad', 'F du Plessis', 'MM Ali', 'SK R...","['RV Uthappa', 'G Gambhir', 'MK Pandey', 'SA Y...",AK Chaudhary,S Ravi
freq,NaN,159,2,76,15,126,119,77,123,599,932,131,509,NaN,19,25,2,2,95,83
mean,8.304852e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.056867,NaN,NaN,NaN,NaN,NaN,NaN
std,3.375678e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21.633109,NaN,NaN,NaN,NaN,NaN,NaN
min,3.359820e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,NaN,NaN
25%,5.012612e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.000000,NaN,NaN,NaN,NaN,NaN,NaN
50%,8.297380e+05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.000000,NaN,NaN,NaN,NaN,NaN,NaN
75%,1.175372e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.000000,NaN,NaN,NaN,NaN,NaN,NaN
max,1.312200e+06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,146.000000,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
ipl_df.shape

(950, 20)

In [ ]:
ipl_df.columns

Index(['ID', 'City', 'Date', 'Season', 'MatchNumber', 'Team1', 'Team2',
       'Venue', 'TossWinner', 'TossDecision', 'SuperOver', 'WinningTeam',
       'WonBy', 'Margin', 'method', 'Player_of_Match', 'Team1Players',
       'Team2Players', 'Umpire1', 'Umpire2'],
      dtype='object')

In [ ]:
ipl_df.columns = ipl_df.columns.str.lower().str.replace('_','')

In [ ]:
ipl_df.columns

Index(['id', 'city', 'date', 'season', 'matchnumber', 'team1', 'team2',
       'venue', 'tosswinner', 'tossdecision', 'superover', 'winningteam',
       'wonby', 'margin', 'method', 'playerofmatch', 'team1players',
       'team2players', 'umpire1', 'umpire2'],
      dtype='object')

In [ ]:
ipl_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             950 non-null    int64
 1   city           899 non-null    object
 2   date           950 non-null    object
 3   season         950 non-null    object
 4   matchnumber    950 non-null    object
 5   team1          950 non-null    object
 6   team2          950 non-null    object
 7   venue          950 non-null    object
 8   tosswinner     950 non-null    object
 9   tossdecision   950 non-null    object
 10  superover      946 non-null    object
 11  winningteam    946 non-null    object
 12  wonby          950 non-null    object
 13  margin         932 non-null    float64
 14  method         19 non-null     object
 15  playerofmatch  946 non-null    object
 16  team1players   950 non-null    object
 17  team2players   950 non-null    object
 18  umpire1        950 non-null    object
 19  umpire2        950 non-null    object
dtypes: float64(1), int64(1), object(18)
memory usage: 148.6+ KB

In [ ]:
ipl_df['date'] = pd.to_datetime(ipl_df['date'])

In [ ]:
ipl_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             950 non-null    int64
 1   city           899 non-null    object
 2   date           950 non-null    datetime64[ns]
 3   season         950 non-null    object
 4   matchnumber    950 non-null    object
 5   team1          950 non-null    object
 6   team2          950 non-null    object
 7   venue          950 non-null    object
 8   tosswinner     950 non-null    object
 9   tossdecision   950 non-null    object
 10  superover      946 non-null    object
 11  winningteam    946 non-null    object
 12  wonby          950 non-null    object
 13  margin         932 non-null    float64
 14  method         19 non-null     object
 15  playerofmatch  946 non-null    object
 16  team1players   950 non-null    object
 17  team2players   950 non-null    object
 18  umpire1        950 non-null    object
 19  umpire2        950 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(1), object(17)
memory usage: 148.6+ KB

In [ ]:
ipl_df.head()

,id,city,date,season,matchnumber,team1,team2,venue,tosswinner,tossdecision,superover,winningteam,wonby,margin,method,playerofmatch,team1players,team2players,umpire1,umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan

In [ ]:
ipl_df['season'] = ipl_df['season'].astype('int')

ValueError: invalid literal for int() with base 10: '2020/21'

In [ ]:
ipl_df['tosswinner'].unique()

array(['Rajasthan Royals', 'Lucknow Super Giants', 'Gujarat Titans',
       'Sunrisers Hyderabad', 'Mumbai Indians', 'Chennai Super Kings',
       'Punjab Kings', 'Kolkata Knight Riders',
       'Royal Challengers Bangalore', 'Delhi Capitals', 'Kings XI Punjab',
       'Delhi Daredevils', 'Rising Pune Supergiant', 'Gujarat Lions',
       'Rising Pune Supergiants', 'Pune Warriors', 'Deccan Chargers',
       'Kochi Tuskers Kerala'], dtype=object)

In [ ]:
cleanup_map = {
    'Rising Pune Supergiants': 'Rising Pune Supergiant'
}

In [ ]:
ipl_df['tosswinner'] = ipl_df['tosswinner'].replace(cleanup_map)

In [ ]:
ipl_df['tosswinner'].unique()

array(['Rajasthan Royals', 'Lucknow Super Giants', 'Gujarat Titans',
       'Sunrisers Hyderabad', 'Mumbai Indians', 'Chennai Super Kings',
       'Punjab Kings', 'Kolkata Knight Riders',
       'Royal Challengers Bangalore', 'Delhi Capitals', 'Kings XI Punjab',
       'Delhi Daredevils', 'Rising Pune Supergiant', 'Gujarat Lions',
       'Pune Warriors', 'Deccan Chargers', 'Kochi Tuskers Kerala'],
      dtype=object)

In [ ]:
ipl_df.head()

,id,city,date,season,matchnumber,team1,team2,venue,tosswinner,tossdecision,superover,winningteam,wonby,margin,method,playerofmatch,team1players,team2players,umpire1,umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan

In [ ]:
ipl_df['superover'].unique()

array(['N', 'Y', nan], dtype=object)

In [ ]:
bool_map = {
    'N': False,
    'Y': True
}

In [ ]:
ipl_df['superover'] = ipl_df['superover'].replace(bool_map).fillna(False)

/var/folders/sj/vg5j80_j3r16b_998tz0pg5w0000gn/T/ipykernel_4017/2605941680.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  ipl_df['superover'] = ipl_df['superover'].replace(bool_map).fillna(False)

In [ ]:
ipl_df['superover'].unique()

array([False,  True])

In [ ]:
ipl_df[ipl_df['season'] == '2020/21']

,id,city,date,season,matchnumber,team1,team2,venue,tosswinner,tossdecision,superover,winningteam,wonby,margin,method,playerofmatch,team1players,team2players,umpire1,umpire2
134,1237181,NaN,2020-11-10,2020/21,Final,Delhi Capitals,Mumbai Indians,Dubai International Cricket Stadium,Delhi Capitals,bat,False,Mumbai Indians,Wickets,5.0,NaN,TA Boult,"['MP Stoinis', 'S Dhawan', 'AM Rahane', 'SS Iy...","['RG Sharma', 'Q de Kock', 'SA Yadav', 'Ishan ...",CB Gaffaney,Nitin Menon
135,1237180,Abu Dhabi,2020-11-08,2020/21,Qualifier 2,Delhi Capitals,Sunrisers Hyderabad,Sheikh Zayed Stadium,Delhi Capitals,bat,False,Delhi Capitals,Runs,17.0,NaN,MP Stoinis,"['MP Stoinis', 'S Dhawan', 'SS Iyer', 'SO Hetm...","['PK Garg', 'DA Warner', 'MK Pandey', 'KS Will...",PR Reiffel,S Ravi
136,1237178,Abu Dhabi,2020-11-06,2020/21,Eliminator,Royal Challengers Bangalore,Sunrisers Hyderabad,Sheikh Zayed Stadium,Sunrisers Hyderabad,field,False,Sunrisers Hyderabad,Wickets,6.0,NaN,KS Williamson,"['V Kohli', 'D Padikkal', 'AJ Finch', 'AB de V...","['DA Warner', 'SP Goswami', 'MK Pandey', 'KS W...",PR Reiffel,S Ravi
137,1237177,NaN,2020-11-05,2020/21,Qualifier 1,Mumbai Indians,Delhi Capitals,Dubai International Cricket Stadium,Delhi Capitals,field,False,Mumbai Indians,Runs,57.0,NaN,JJ Bumrah,"['Q de Kock', 'RG Sharma', 'SA Yadav', 'Ishan ...","['PP Shaw', 'S Dhawan', 'AM Rahane', 'SS Iyer'...",CB Gaffaney,Nitin Menon
138,1216495,NaN,2020-11-03,2020/21,56,Mumbai Indians,Sunrisers Hyderabad,Sharjah Cricket Stadium,Sunrisers Hyderabad,field,False,Sunrisers Hyderabad,Wickets,10.0,NaN,S Nadeem,"['RG Sharma', 'Q de Kock', 'SA Yadav', 'Ishan ...","['DA Warner', 'WP Saha', 'MK Pandey', 'KS Will...",C Shamshuddin,RK Illingworth
139,1216505,Abu Dhabi,2020-11-02,2020/21,55,Royal Challengers Bangalore,Delhi Capitals,Sheikh Zayed Stadium,Delhi Capitals,field,False,Delhi Capitals,Wickets,6.0,NaN,A Nortje,"['JR Philippe', 'D Padikkal', 'V Kohli', 'AB d...","['PP Shaw', 'S Dhawan', 'AM Rahane', 'SS Iyer'...",CB Gaffaney,S Ravi
140,1216530,NaN,2020-11-01,2020/21,54,Kolkata Knight Riders,Rajasthan Royals,Dubai International Cricket Stadium,Rajasthan Royals,field,False,Kolkata Knight Riders,Runs,60.0,NaN,PJ Cummins,"['Shubman Gill', 'N Rana', 'RA Tripathi', 'SP ...","['RV Uthappa', 'BA Stokes', 'SPD Smith', 'SV S...",Nitin Menon,PR Reiffel
141,1216506,Abu Dhabi,2020-11-01,2020/21,53,Kings XI Punjab,Chennai Super Kings,Sheikh Zayed Stadium,Chennai Super Kings,field,False,Chennai Super Kings,Wickets,9.0,NaN,RD Gaikwad,"['KL Rahul', 'MA Agarwal', 'CH Gayle', 'N Poor...","['RD Gaikwad', 'F du Plessis', 'AT Rayudu', 'M...",PG Pathak,VK Sharma
142,1216535,NaN,2020-10-31,2020/21,51,Delhi Capitals,Mumbai Indians,Dubai International Cricket Stadium,Mumbai Indians,field,False,Mumbai Indians,Wickets,9.0,NaN,Ishan Kishan,"['PP Shaw', 'S Dhawan', 'SS Iyer', 'RR Pant', ...","['Ishan Kishan', 'Q de Kock', 'SA Yadav', 'SS ...",YC Barde,PR Reiffel
143,1216502,NaN,2020-10-31,2020/21,52,Royal Challengers Bangalore,Sunrisers Hyderabad,Sharjah Cricket Stadium,Sunrisers Hyderabad,field,False,Sunrisers Hyderabad,Wickets,5.0,NaN,Sandeep Sharma,"['JR Philippe', 'D Padikkal', 'V Kohli', 'AB d...","['DA Warner', 'WP Saha', 'MK Pandey', 'KS Will...",KN Ananthapadmanabhan,K Srinivasan
144,1216537,Abu Dhabi,2020-10-30,2020/21,50,Kings XI Punjab,Rajasthan Royals,Sheikh Zayed Stadium,Rajasthan Royals,field,False,Rajasthan Royals,Wickets,7.0,NaN,BA Stokes,"['KL Rahul', 'Mandeep Singh', 'CH Gayle', 'N P...","['RV Uthappa', 'BA Stokes', 'SV Samson', 'SPD ...",CB Gaffaney,S Ravi
145,1216536,NaN,2020-10-29,2020/21,49,Kolkata Knight Riders,Chennai Super Kings,Dubai International Cricket Stadium,Chennai Super Kings,field,False,Chennai Super Kings,Wickets,6.0,NaN,RD Gaikwad,"['Shubman Gill', 'N Rana', 'SP Narine', 'RK Si...","['SR Watson', 'RD Gaikwad', 'AT Rayudu', 'MS D...",C Shamshuddin,RK Illingworth
146,1216499,Abu Dhabi,2020-10-28,2020/21,48,Royal Challengers Bangalore,Mumbai Indians,Sheikh Zayed Stadium,Mumbai Indians,field,False,Mumbai Indians,Wickets,5.0,NaN,SA Yadav,"['JR Philippe', 'D Padikkal', 'V Kohli', 'AB d...","['Q de Kock', 'Ishan Kishan', 'SA Yadav', 'SS ...",UV Gandhe,CB Gaffaney
147,1216524,NaN,2020-10-27,2020/21,47,Sunrisers Hyderabad,Delhi Capitals,Dubai International Cricket Stadium,Delhi Capitals,field,False,Sunrisers Hyderabad,Runs,88.0,NaN,WP Saha,"['DA Warner', 'WP Saha', 'MK Pandey', 'KS Will...","['AM Rahane', 'S Dhawan', 'MP Stoinis', 'SO He...",AK Chaudhary,Nitin Menon
148,1216520,NaN,2020-10-26,2020/21,46,Kolkata Knight Riders,Kings XI Punjab,Sharjah Cricket Stadium,Kings XI Punjab,field,False,Kings XI Punjab,Wickets,8.0,NaN,CH Gayle,"['Shubman Gill', 'N Rana', 'RA Tripathi', 'KD ...","['KL Rahul', 'Mandeep Singh', 'CH Gayle', 'N P...",KN Ananthapadmanabhan,RK Illingworth
149,1216541,Abu Dhabi,2020-10-25,2020/21,45,Mumbai Indians,Rajasthan Royals,Sheikh Zayed Stadium,Mumbai Indians,bat,False,Rajasthan Royals,Wickets,8.0,NaN,BA Stokes,"['Ishan Kishan', 'Q de Kock', 'SA Yadav', 'SS ...","['RV Uthappa', 'BA Stokes', 'SPD Smith', 'SV S...",UV Gandhe,VK Sharma
150,1216544,NaN,2020-10-25,2020/21,44,Royal Challengers Bangalore,Chennai Super Kings,Dubai International Cricket Stadium,Royal Challengers Bangalore,bat,False,Chennai Super Kings,Wickets,8.0,NaN,RD Gaikwad,"['D Padikkal', 'AJ Finch', 'V Kohli', 'AB de V...","['RD Gaikwad', 'F du Plessis', 'AT Rayudu', 'M...",C Shamshuddin,RK Illingworth
151,1216498,NaN,2020-10-24,2020/21,43,Kings XI Punjab,Sunrisers Hyderabad,Dubai International Cricket Stadium,Sunrisers Hyderabad,field,False,Kings XI Punjab,Runs,12.0,NaN,CJ Jordan,"['KL Rahul', 'Mandeep Singh', 'CH Gayle', 'N P...","['DA Warner', 'JM Bairstow', 'MK Pandey', 'Abd...",AY Dandekar,PR Reiffel
152,1216497,Abu Dhabi,2020-10-24,2020/21,42,Kolkata Knight Riders,Delhi Capitals,Sheikh Zayed Stadium,Delhi Capitals,field,False,Kolkata Knight Riders,Runs,59.0,NaN,CV Varun,"['Shubman Gill', 'N Rana', 'RA Tripathi', 'KD ...","['AM Rahane', 'S Dhawan', 'SS Iyer', 'RR Pant'...",CB Gaffaney,PG Pathak
153,1216521,NaN,2020-10-23,2020/21,41,Chennai Super Kings,Mumbai Indians,Sharjah Cricket Stadium,Mumbai Indians,field,False,Mumbai Indians,Wickets,10.0,NaN,TA Boult,"['RD Gaikwad', 'F du Plessis', 'AT Rayudu', 'N...","['Q de Kock', 'Ishan Kishan', 'SA Yadav', 'SS ...",C Shamshuddin,VA Kulkarni
154,1216518,NaN,2020-10-22,2020/21,40,Rajasthan Royals,Sunrisers Hyderabad,Dubai International Cricket Stadium,Sunrisers Hyderabad,field,False,Sunrisers Hyderabad,Wickets,8.0,NaN,MK Pandey,"['RV Uthappa', 'BA Stokes', 'SV Samson', 'JC B...","['DA Warner', 'JM Bairstow', 'MK Pandey', 'V S...",Nitin Menon,PR Reiffel
155,1216494,Abu Dhabi,2020-10-21,2020/21,39,Kolkata Knight Riders,Royal Challengers Bangalore,Sheikh Zayed Stadium,Kolkata Knight Riders,bat,False,Royal Challengers Bangalore,Wickets,8.0,NaN,Mohammed Siraj,"['Shubman Gill', 'RA Tripathi', 'N Rana', 'T B...","['D Padikkal', 'AJ Finch', 'Gurkeerat Singh', ...",VK Sharma,S Ravi
156,1216546,NaN,2020-10-20,2020/21,38,Delhi Capitals,Kings XI Punjab,Dubai International Cricket Stadium,Delhi Capitals,bat,False,Kings XI Punjab,Wickets,5.0,NaN,S Dhawan,"['PP Shaw', 'S Dhawan', 'SS Iyer', 'RR Pant', ...","['KL Rahul', 'MA Agarwal', 'CH Gayle', 'N Poor...",C Shamshuddin,RK Illingworth
157,1216533,Abu Dhabi,2020-10-19,2020/21,37,Chennai Super Kings,Rajasthan Royals,Sheikh Zayed Stadium,Chennai Super Kings,bat,False,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['SM Curran', 'F du Plessis', 'SR Watson', 'AT...","['BA Stokes', 'RV Uthappa', 'SV Samson', 'SPD ...",CB Gaffaney,VK Sharma
158,1216512,Abu Dhabi,2020-10-18,2020/21,35,Kolkata Knight Riders,Sunrisers Hyderabad,Sheikh Zayed Stadium,Sunrisers Hyderabad,field,True,Kolkata Knight Riders,SuperOver,NaN,NaN,LH Ferguson,"['Shubman Gill', 'RA Tripathi', 'N Rana', 'AD ...","['JM Bairstow', 'KS Williamson', 'PK Garg', 'D...",PG Pathak,S Ravi
159,1216517,NaN,2020-10-18,2020/21,36,Mumbai Indians,Kings XI Punjab,Dubai International Cricket Stadium,Mumbai Indians,bat,True,Kings XI Punjab,SuperOver,NaN,NaN,KL Rahul,"['RG Sharma', 'Q de Kock', 'SA Yadav', 'Ishan ...","['KL Rahul', 'MA Agarwal', 'CH Gayle', 'N Poor...",Nitin Menon,PR Reiffel
160,1216522,NaN,2020-10-17,2020/21,33,Rajasthan Royals,Royal Challengers Bangalore,Dubai International Cricket Stadium,Rajasthan Royals,bat,False,Royal Challengers Bangalore,Wickets,7.0,NaN,AB de Villiers,"['RV Uthappa', 'BA Stokes', 'SV Samson', 'SPD ...","['D Padikkal', 'AJ Finch', 'V Kohli', 'AB de V...",AK Chaudhary,Nitin Menon
161,1216509,NaN,2020-10-17,2020/21,34,Chennai Super Kings,Delhi Capitals,Sharjah Cricket Stadium,Chennai Super Kings,bat,False,Delhi Capitals,Wickets,5.0,NaN,S Dhawan,"['SM Curran', 'F du Plessis', 'SR Watson', 'AT...","['PP Shaw', 'S Dhawan', 'AM Rahane', 'SS Iyer'...",KN Ananthapadmanabhan,RK Illingworth
162,1216526,Abu Dhabi,2020-10-16,2020/21,32,Kolkata Knight Riders,Mumbai Indians,Sheikh Zayed Stadium,Kolkata Knight Riders,bat,False,Mumbai Indians,Wickets,8.0,NaN,Q de Kock,"['RA Tripathi', 'Shubman Gill', 'N Rana', 'KD ...","['RG Sharma', 'Q de Kock', 'SA Yadav', 'HH Pan...",CB Gaffaney,VK Sharma
163,1216531,NaN,2020-10-15,2020/21,31,Royal Challengers Bangalore,Kings XI Punjab,Sharjah Cricket Stadium,Royal Challengers Bangalore,bat,False,Kings XI Punjab,Wickets,8.0,NaN,KL Rahul,"['AJ Finch', 'D Padikkal', 'V Kohli', 'Washing...","['KL Rahul', 'MA Agarwal', 'CH Gayle', 'N Poor...",KN Ananthapadmanabhan,C Shamshuddin
164,1216543,NaN,2020-10-14,2020/21,30,Delhi Capitals,Rajasthan Royals,Dubai International Cricket Stadium,Delhi Capitals,bat,False,Delhi Capitals,Runs,13.0,NaN,A Nortje,"['PP Shaw', 'S Dhawan', 'AM Rahane', 'SS Iyer'...","['BA Stokes', 'JC Buttler', 'SPD Smith', 'SV S...",AK Chaudhary,Nitin Menon
165,1216528,NaN,2020-10-13,2020/21,29,Chennai Super Kings,Sunrisers Hyderabad,Dubai International Cricket Stadium,Chennai Super Kings,bat,False,Chennai Super Kings,Runs,20.0,NaN,RA Jadeja,"['SM Curran', 'F du Plessis', 'SR Watson', 'AT...","['DA Warner', 'JM Bairstow', 'MK Pandey', 'KS ...",AK Chaudhary,PR Reiffel
166,1216540,NaN,2020-10-12,2020/21,28,Royal Challengers Bangalore,Kolkata Knight Riders,Sharjah Cricket Stadium,Royal Challengers Bangalore,bat,False,Royal Challengers Bangalore,Runs,82.0,NaN,AB de Villiers,"['AJ Finch', 'D Padikkal', 'V Kohli', 'AB de V...","['T Banton', 'Shubman Gill', 'N Rana', 'EJG Mo...",RK Illingworth,K Srinivasan
167,1216507,NaN,2020-10-11,2020/21,26,Sunrisers Hyderabad,Rajasthan Royals,Dubai International Cricket Stadium,Sunrisers Hyderabad,bat,False,Rajasthan Royals,Wickets,5.0,NaN,R Tewatia,"['DA Warner', 'JM Bairstow', 'MK Pandey', 'KS ...","['BA Stokes', 'JC Buttler', 'SPD Smith', 'SV S...",YC Barde,PR Reiffel
168,1216529,Abu Dhabi,2020-10-11,2020/21,27,Delhi Capitals,Mumbai Indians,Sheikh Zayed Stadium,Delhi Capitals,bat,False,Mumbai Indians,Wickets,5.0,NaN,Q de Kock,"['PP Shaw', 'S Dhawan', 'AM Rahane', 'SS Iyer'...","['RG Sharma', 'Q de Kock', 'SA Yadav', 'Ishan ...",CB Gaffaney,S Ravi
169,1216523,Abu Dhabi,2020-10-10,2020/21,24,Kolkata Knight Riders,Kings XI Punjab,Sheikh Zayed Stadium,Kolkata Knight Riders,bat,False,Kolkata Knight Riders,Runs,2.0,NaN,KD Karthik,"['RA Tripathi', 'Shubman Gill', 'N Rana', 'EJG...","['KL Rahul', 'MA Agarwal', 'N Pooran', 'P Simr...",UV Gandhe,CB Gaffaney
170,1216525,NaN,2020-10-10,2020/21,25,Royal Challengers Bangalore,Chennai Super Kings,Dubai International Cricket Stadium,Royal Challengers Bangalore,bat,False,Royal Challengers Bangalore,Runs,37.0,NaN,V Kohli,"['D Padikkal', 'AJ Finch', 'V Kohli', 'AB de V...","['SR Watson', 'F du Plessis', 'AT Rayudu', 'N ...",AK Chaudhary,PR Reiffel
171,1216500,NaN,2020-10-09,2020/21,23,Delhi Capitals,Rajasthan Royals,Sharjah Cricket Stadium,Rajasthan Royals,field,False,Delhi Capitals,Runs,46.0,NaN,R Ashwin,"['PP Shaw', 'S Dhawan', 'SS Iyer', 'RR Pant', ...","['YBK Jaiswal', 'JC Buttler', 'SPD Smith', 'SV...",KN Ananthapadmanabhan,C Shamshuddin
172,1216542,NaN,2020-10-08,2020/21,22,Sunrisers Hyderabad,Kings XI Punjab,Dubai International Cricket Stadium,Sunrisers Hyderabad,bat,False,Sunrisers Hyderabad,Runs,69.0,NaN,JM Bairstow,"['DA Warner', 'JM Bairstow', 'Abdul Samad', 'M...","['KL Rahul', 'MA Agarwal', 'P Simran Singh', '...",AK Chaudhary,Nitin Menon
173,1216501,Abu Dhabi,2020-10-07,2020/21,21,Kolkata Knight Riders,Chennai Super Kings,Sheikh Zayed Stadium,Kolkata Knight Riders,bat,False,Kolkata Knight Riders,Runs,10.0,NaN,RA Tripathi,"['RA Tripathi', 'Shubman Gill', 'N Rana', 'SP ...","['SR Watson', 'F du Plessis', 'AT Rayudu', 'MS...",KN Ananthapadmanabhan,RK Illingworth
174,1216511,Abu Dhabi,2020-10-06,2020/21,20,Mumbai Indians,Rajasthan Royals,Sheikh Zayed Stadium,Mumbai Indians,bat,False,Mumbai Indians,Runs,57.0,NaN,SA Yadav,"['Q de Kock', 'RG Sharma', 'SA Yadav', 'Ishan ...","['YBK Jaiswal', 'JC Buttler', 'SPD Smith', 'SV...",VK Sharma,S Ravi
175,1216519,NaN,2020-10-05,2020/21,19,Delhi Capitals,Royal Challengers Bangalore,Dubai International Cricket Stadium,Royal Challengers Bangalore,field,False,Delhi Capitals,Runs,59.0,NaN,AR Patel,"['PP Shaw', 'S Dhawan', 'SS Iyer', 'RR Pant', ...","['D Padikkal', 'AJ Finch', 'V Kohli', 'AB de V...",Nitin Menon,YC Barde
176,1216513,NaN,2020-10-04,2020/21,18,Kings XI Punjab,Chennai Super Kings,Dubai International Cricket Stadium,Kings XI Punjab,bat,False,Chennai Super Kings,Wickets,10.0,NaN,SR Watson,"['KL Rahul', 'MA Agarwal', 'Mandeep Singh', 'N...","['SR Watson', 'F du Plessis', 'AT Rayudu', 'KM...",AY Dandekar,Nitin Menon
177,1216538,NaN,2020-10-04,2020/21,17,Mumbai Indians,Sunrisers Hyderabad,Sharjah Cricket Stadium,Mumbai Indians,bat,False,Mumbai Indians,Runs,34.0,NaN,TA Boult,"['RG Sharma', 'Q de Kock', 'SA Yadav', 'Ishan ...","['DA Warner', 'JM Bairstow', 'MK Pandey', 'KS ...",KN Ananthapadmanabhan,RK Illingworth
178,1216514,Abu Dhabi,2020-10-03,2020/21,15,Rajasthan Royals,Royal Challengers Bangalore,Sheikh Zayed Stadium,Rajasthan Royals,bat,False,Royal Challengers Bangalore,Wickets,8.0,NaN,YS Chahal,"['JC Buttler', 'SPD Smith', 'SV Samson', 'RV U...","['D Padikkal', 'AJ Finch', 'V Kohli', 'AB de V...",CB Gaffaney,S Ravi
179,1216515,NaN,2020-10-03,2020/21,16,Delhi Capitals,Kolkata Knight Riders,Sharjah Cricket Stadium,Kolkata Knight Riders,field,False,Delhi Capitals,Runs,18.0,NaN,SS Iyer,"['PP Shaw', 'S Dhawan', 'SS Iyer', 'RR Pant', ...","['Shubman Gill', 'SP Narine', 'N Rana', 'AD Ru...",VA Kulkarni,RK Illingworth
180,1216516,NaN,2020-10-02,2020/21,14,Sunrisers Hyderabad,Chennai Super Kings,Dubai International Cricket Stadium,Sunrisers Hyderabad,bat,False,Sunrisers Hyderabad,Runs,7.0,NaN,PK Garg,"['DA Warner', 'JM Bairstow', 'MK Pandey', 'KS ...","['F du Plessis', 'SR Watson', 'AT Rayudu', 'KM...",AK Chaudhary,PR Reiffel
181,1216503,Abu Dhabi,2020-10-01,2020/21,13,Mumbai Indians,Kings XI Punjab,Sheikh Zayed Stadium,Kings XI Punjab,field,False,Mumbai Indians,Runs,48.0,NaN,KA Pollard,"['Q de Kock', 'RG Sharma', 'SA Yadav', 'Ishan ...","['KL Rahul', 'MA Agarwal', 'KK Nair', 'N Poora...",VK Sharma,S Ravi
182,1216504,NaN,2020-09-30,2020/21,12,Kolkata Knight Riders,Rajasthan Royals,Dubai International Cricket Stadium,Rajasthan Royals,field,False,Kolkata Knight Riders,Runs,37.0,NaN,Shivam Mavi,"['Shubman Gill', 'SP Narine', 'N Rana', 'AD Ru...","['JC Buttler', 'SPD Smith', 'SV Samson', 'RV U...",KN Ananthapadmanabhan,C Shamshuddin
183,1216532,Abu Dhabi,2020-09-29,2020/21,11,Sunrisers Hyderabad,Delhi Capitals,Sheikh Zayed Stadium,Delhi Capitals,field,False,Sunrisers Hyderabad,Runs,15.0,NaN,Rashid Khan,"['DA Warner', 'JM Bairstow', 'MK Pandey', 'KS ...","['PP Shaw', 'S Dhawan', 'SS Iyer', 'RR Pant', ...",VK Sharma,S Ravi
184,1216547,NaN,2020-09-28,2020/21,10,Royal Challengers Bangalore,Mumbai Indians,Dubai International Cricket Stadium,Mumbai Indians,field,True,Royal Challengers Bangalore,SuperOver,NaN,NaN,AB de Villiers,"['D Padikkal', 'AJ Finch', 'V Kohli', 'AB de V...","['RG Sharma', 'Q de Kock', 'SA Yadav', 'Ishan ...",Nitin Menon,PR Reiffel
185,1216527,NaN,2020-09-27,2020/21,9,Kings XI Punjab,Rajasthan Royals,Sharjah Cricket Stadium,Rajasthan Royals,field,False,Rajasthan Royals,Wickets,4.0,NaN,SV Samson,"['KL Rahul', 'MA Agarwal', 'GJ Maxwell', 'N Po...","['JC Buttler', 'SPD Smith', 'SV Samson', 'R Te...",RK Illingworth,K Srinivasan
186,1216545,Abu Dhabi,2020-09-26,2020/21,8,Sunrisers Hyderabad,Kolkata Knight Riders,Sheikh Zayed Stadium,Sunrisers Hyderabad,bat,False,Kolkata Knight Riders,Wickets,7.0,NaN,Shubman Gill,"['DA Warner', 'JM Bairstow', 'MK Pandey', 'WP ...","['Shubman Gill', 'SP Narine', 'N Rana', 'KD Ka...",CB Gaffaney,VK Sharma
187,1216539,NaN,2020-09-25,2020/21,7,Delhi Capitals,Chennai Super Kings,Dubai International Cricket Stadium,Chennai Super Kings,field,False,Delhi Capitals,Runs,44.0,NaN,PP Shaw,"['PP Shaw', 'S Dhawan', 'RR Pant', 'SS Iyer', ...","['M Vijay', 'SR Watson', 'F du Plessis', 'RD G...",KN Ananthapadmanabhan,RK Illingworth
188,1216510,NaN,2020-09-24,2020/21,6,Kings XI Punjab,Royal Challengers Bangalore,Dubai International Cricket Stadium,Royal Challengers Bangalore,field,False,Kings XI Punjab,Runs,97.0,NaN,KL Rahul,"['KL Rahul', 'MA Agarwal', 'N Pooran', 'GJ Max...","['D Padikkal', 'AJ Finch', 'JR Philippe', 'V K...",AK Chaudhary,PR Reiffel
189,1216508,Abu Dhabi,2020-09-23,2020/21,5,Mumbai Indians,Kolkata Knight Riders,Sheikh Zayed Stadium,Kolkata Knight Riders,field,False,Mumbai Indians,Runs,49.0,NaN,RG Sharma,"['Q de Kock', 'RG Sharma', 'SA Yadav', 'SS Tiw...","['Shubman Gill', 'SP Narine', 'KD Karthik', 'N...",CB Gaffaney,S Ravi
190,1216496,NaN,2020-09-22,2020/21,4,Rajasthan Royals,Chennai Super Kings,Sharjah Cricket Stadium,Chennai Super Kings,field,False,Rajasthan Royals,Runs,16.0,NaN,SV Samson,"['YBK Jaiswal', 'SPD Smith', 'SV Samson', 'DA ...","['M Vijay', 'SR Watson', 'F du Plessis', 'SM C...",C Shamshuddin,VA Kulkarni
191,1216534,NaN,2020-09-21,2020/21,3,Royal Challengers Bangalore,Sunrisers Hyderabad,Dubai International Cricket Stadium,Sunrisers Hyderabad,field,False,Royal Challengers Bangalore,Runs,10.0,NaN,YS Chahal,"['D Padikkal', 'AJ Finch', 'V Kohli', 'AB de V...","['DA Warner', 'JM Bairstow', 'MK Pandey', 'PK ...",AY Dandekar,Nitin Menon
192,1216493,NaN,2020-09-20,2020/21,2,Delhi Capitals,Kings XI Punjab,Dubai International Cricket Stadium,Kings XI Punjab,field,True,Delhi Capitals,SuperOver,NaN,NaN,MP Stoinis,"['PP Shaw', 'S Dhawan', 'SO Hetmyer', 'SS Iyer...","['KL Rahul', 'MA Agarwal', 'KK Nair', 'N Poora...",AK Chaudhary,Nitin Menon
193,1216492,Abu Dhabi,2020-09-19,2020/21,1,Mumbai Indians,Chennai Super Kings,Sheikh Zayed Stadium,Chennai Super Kings,field,False,Chennai Super Kings,Wickets,5.0,NaN,AT Rayudu,"['RG Sharma', 'Q de Kock', 'SA Yadav', 'SS Tiw...","['M Vijay', 'SR Watson', 'F du Plessis', 'AT R...",CB Gaffaney,VK Sharma

In [ ]:
ipl_df.head(10)

,id,city,date,season,matchnumber,team1,team2,venue,tosswinner,tossdecision,superover,winningteam,wonby,margin,method,playerofmatch,team1players,team2players,umpire1,umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,False,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,False,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,False,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,False,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,False,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
5,1304115,Mumbai,2022-05-21,2022,69,Delhi Capitals,Mumbai Indians,"Wankhede Stadium, Mumbai",Mumbai Indians,field,False,Mumbai Indians,Wickets,5.0,NaN,JJ Bumrah,"['PP Shaw', 'DA Warner', 'MR Marsh', 'RR Pant'...","['Ishan Kishan', 'RG Sharma', 'D Brevis', 'Til...",Nitin Menon,Tapan Sharma
6,1304114,Mumbai,2022-05-20,2022,68,Chennai Super Kings,Rajasthan Royals,"Brabourne Stadium, Mumbai",Chennai Super Kings,bat,False,Rajasthan Royals,Wickets,5.0,NaN,R Ashwin,"['RD Gaikwad', 'DP Conway', 'MM Ali', 'N Jagad...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,NA Patwardhan
7,1304113,Mumbai,2022-05-19,2022,67,Gujarat Titans,Royal Challengers Bangalore,"Wankhede Stadium, Mumbai",Gujarat Titans,bat,False,Royal Challengers Bangalore,Wickets,8.0,NaN,V Kohli,"['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...","['V Kohli', 'F du Plessis', 'GJ Maxwell', 'KD ...",KN Ananthapadmanabhan,GR Sadashiv Iyer
8,1304112,Navi Mumbai,2022-05-18,2022,66,Lucknow Super Giants,Kolkata Knight Riders,"Dr DY Patil Sports Academy, Mumbai",Lucknow Super Giants,bat,False,Lucknow Super Giants,Runs,2.0,NaN,Q de Kock,"['Q de Kock', 'KL Rahul', 'E Lewis', 'DJ Hooda...","['VR Iyer', 'A Tomar', 'N Rana', 'SS Iyer', 'S...",R Pandit,YC Barde
9,1304111,Mumbai,2022-05-17,2022,65,Sunrisers Hyderabad,Mumbai Indians,"Wankhede Stadium, Mumbai",Mumbai Indians,field,False,Sunrisers Hyderabad,Runs,3.0,NaN,RA Tripathi,"['Abhishek Sharma', 'PK Garg', 'RA Tripathi', ...","['RG Sharma', 'Ishan Kishan', 'DR Sams', 'Tila...",CB Gaffaney,N Pandit

In [ ]:
ipl_df.sample(20)

,id,city,date,season,matchnumber,team1,team2,venue,tosswinner,tossdecision,superover,winningteam,wonby,margin,method,playerofmatch,team1players,team2players,umpire1,umpire2
822,419118,Ahmedabad,2010-03-20,2009/10,13,Rajasthan Royals,Kolkata Knight Riders,"Sardar Patel Stadium, Motera",Rajasthan Royals,bat,False,Rajasthan Royals,Runs,34.0,NaN,AA Jhunjhunwala,"['MJ Lumb', 'NV Ojha', 'FY Fazal', 'AA Jhunjhu...","['MK Tiwary', 'BJ Hodge', 'CA Pujara', 'SC Gan...",RE Koertzen,RB Tiffin
28,1304092,Pune,2022-05-01,2022,46,Chennai Super Kings,Sunrisers Hyderabad,"Maharashtra Cricket Association Stadium, Pune",Sunrisers Hyderabad,field,False,Chennai Super Kings,Runs,13.0,NaN,RD Gaikwad,"['RD Gaikwad', 'DP Conway', 'MS Dhoni', 'RA Ja...","['Abhishek Sharma', 'KS Williamson', 'RA Tripa...",AK Chaudhary,KN Ananthapadmanabhan
303,1136571,Bengaluru,2018-04-15,2018,11,Rajasthan Royals,Royal Challengers Bangalore,M.Chinnaswamy Stadium,Royal Challengers Bangalore,field,False,Rajasthan Royals,Runs,19.0,NaN,SV Samson,"['AM Rahane', 'DJM Short', 'SV Samson', 'BA St...","['BB McCullum', 'Q de Kock', 'V Kohli', 'AB de...",C Shamshuddin,S Ravi
657,548353,Kolkata,2012-05-05,2012,47,Kolkata Knight Riders,Pune Warriors,Eden Gardens,Kolkata Knight Riders,bat,False,Kolkata Knight Riders,Runs,7.0,NaN,SP Narine,"['G Gambhir', 'BB McCullum', 'YK Pathan', 'JH ...","['RV Uthappa', 'MJ Clarke', 'MK Pandey', 'SPD ...",BF Bowden,SK Tarapore
103,1254087,Abu Dhabi,2021-09-20,2021,31,Royal Challengers Bangalore,Kolkata Knight Riders,"Zayed Cricket Stadium, Abu Dhabi",Royal Challengers Bangalore,bat,False,Kolkata Knight Riders,Wickets,9.0,NaN,CV Varun,"['V Kohli', 'D Padikkal', 'KS Bharat', 'GJ Max...","['Shubman Gill', 'VR Iyer', 'AD Russell', 'N R...",CB Gaffaney,S Ravi
361,1082602,Bangalore,2017-04-14,2017,12,Royal Challengers Bangalore,Mumbai Indians,M Chinnaswamy Stadium,Mumbai Indians,field,False,Mumbai Indians,Wickets,4.0,NaN,KA Pollard,"['CH Gayle', 'V Kohli', 'AB de Villiers', 'KM ...","['PA Patel', 'JC Buttler', 'RG Sharma', 'MJ Mc...",KN Ananthapadmanabhan,AK Chaudhary
690,548317,Mumbai,2012-04-11,2012,12,Mumbai Indians,Rajasthan Royals,Wankhede Stadium,Rajasthan Royals,field,False,Mumbai Indians,Runs,27.0,NaN,KA Pollard,"['RE Levi', 'TL Suman', 'RG Sharma', 'AT Rayud...","['R Dravid', 'AM Rahane', 'SP Goswami', 'OA Sh...",Aleem Dar,BNJ Oxenford
901,336033,Chennai,2008-05-24,2007/08,49,Chennai Super Kings,Rajasthan Royals,"MA Chidambaram Stadium, Chepauk",Rajasthan Royals,bat,False,Rajasthan Royals,Runs,10.0,NaN,JA Morkel,"['PA Patel', 'SP Fleming', 'SK Raina', 'JA Mor...","['GC Smith', 'SA Asnodkar', 'Kamran Akmal', 'Y...",DJ Harper,SL Shastri
881,392192,Durban,2009-04-25,2009,12,Deccan Chargers,Mumbai Indians,Kingsmead,Deccan Chargers,bat,False,Deccan Chargers,Runs,12.0,NaN,PP Ojha,"['AC Gilchrist', 'HH Gibbs', 'DR Smith', 'RG S...","['ST Jayasuriya', 'SR Tendulkar', 'JP Duminy',...",HDPK Dharmasena,SJA Taufel
358,1082605,Delhi,2017-04-15,2017,15,Delhi Daredevils,Kings XI Punjab,Feroz Shah Kotla,Delhi Daredevils,bat,False,Delhi Daredevils,Runs,51.0,NaN,CJ Anderson,"['SV Samson', 'SW Billings', 'KK Nair', 'SS Iy...","['M Vohra', 'HM Amla', 'WP Saha', 'EJG Morgan'...",YC Barde,Nitin Menon
874,392200,Durban,2009-04-29,2009,20,Kings XI Punjab,Mumbai Indians,Kingsmead,Kings XI Punjab,bat,False,Kings XI Punjab,Runs,3.0,NaN,KC Sangakkara,"['RS Bopara', 'K Goel', 'KC Sangakkara', 'Yuvr...","['ST Jayasuriya', 'SR Tendulkar', 'S Dhawan', ...",MR Benson,SL Shastri
268,1136606,Pune,2018-05-13,2018,46,Sunrisers Hyderabad,Chennai Super Kings,Maharashtra Cricket Association Stadium,Chennai Super Kings,field,False,Chennai Super Kings,Wickets,8.0,NaN,AT Rayudu,"['S Dhawan', 'AD Hales', 'KS Williamson', 'MK ...","['SR Watson', 'AT Rayudu', 'SK Raina', 'MS Dho...",M Erasmus,YC Barde
147,1216524,NaN,2020-10-27,2020/21,47,Sunrisers Hyderabad,Delhi Capitals,Dubai International Cricket Stadium,Delhi Capitals,field,False,Sunrisers Hyderabad,Runs,88.0,NaN,WP Saha,"['DA Warner', 'WP Saha', 'MK Pandey', 'KS Will...","['AM Rahane', 'S Dhawan', 'MP Stoinis', 'SO He...",AK Chaudhary,Nitin Menon
104,1254104,Dubai,2021-09-19,2021,30,Chennai Super Kings,Mumbai Indians,Dubai International Cricket Stadium,Chennai Super Kings,bat,False,Chennai Super Kings,Runs,20.0,NaN,RD Gaikwad,"['RD Gaikwad', 'F du Plessis', 'MM Ali', 'AT R...","['Q de Kock', 'Anmolpreet Singh', 'SA Yadav', ...",Nitin Menon,RK Illingworth
542,729297,NaN,2014-04-23,2014,10,Rajasthan Royals,Chennai Super Kings,Dubai International Cricket Stadium,Rajasthan Royals,field,False,Chennai Super Kings,Runs,7.0,NaN,RA Jadeja,"['AM Nayar', 'AM Rahane', 'SV Samson', 'SR Wat...","['DR Smith', 'BB McCullum', 'SK Raina', 'F du ...",HDPK Dharmasena,RK Illingworth
253,1175356,Chennai,2019-03-23,2019,1,Royal Challengers Bangalore,Chennai Super Kings,MA Chidambaram Stadium,Chennai Super Kings,field,False,Chennai Super Kings,Wickets,7.0,NaN,Harbhajan Singh,"['V Kohli', 'PA Patel', 'MM Ali', 'AB de Villi...","['SR Watson', 'AT Rayudu', 'SK Raina', 'KM Jad...",AY Dandekar,BNJ Oxenford
601,598023,Bangalore,2013-04-20,2013,27,Royal Challengers Bangalore,Rajasthan Royals,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,False,Royal Challengers Bangalore,Wickets,7.0,NaN,R Vinay Kumar,"['TM Dilshan', 'CH Gayle', 'V Kohli', 'AB de V...","['SR Watson', 'AM Rahane', 'R Dravid', 'STR Bi...",Aleem Dar,C Shamshuddin
841,392233,Durban,2009-05-20,2009,53,Kolkata Knight Riders,Rajasthan Royals,Kingsmead,Kolkata Knight Riders,field,False,Kolkata Knight Riders,Wickets,4.0,NaN,LR Shukla,"['BB McCullum', 'SC Ganguly', 'BJ Hodge', 'Yas...","['NV Ojha', 'RJ Quiney', 'SA Asnodkar', 'NK Pa...",BG Jerling,SJA Taufel
536,729309,NaN,2014-04-27,2014,16,Delhi Daredevils,Mumbai Indians,Sharjah Cricket Stadium,Mumbai Indians,bat,False,Delhi Daredevils,Wickets,6.0,NaN,M Vijay,"['Q de Kock', 'M Vijay', 'JP Duminy', 'KP Piet...","['RG Sharma', 'AP Tare', 'CJ Anderson', 'AT Ra...",Aleem Dar,VA Kulkarni
162,1216526,Abu Dhabi,2020-10-16,2020/21,32,Kolkata Knight Riders,Mumbai Indians,Sheikh Zayed Stadium,Kolkata Knight Riders,bat,False,Mumbai Indians,Wickets,8.0,NaN,Q de Kock,"['RA Tripathi', 'Shubman Gill', 'N Rana', 'KD ...","['RG Sharma', 'Q de Kock', 'SA Yadav', 'HH Pan...",CB Gaffaney,VK Sharma

In [ ]:
ipl_df.sort_values(by='margin',ascending=False)

,id,city,date,season,matchnumber,team1,team2,venue,tosswinner,tossdecision,superover,winningteam,wonby,margin,method,playerofmatch,team1players,team2players,umpire1,umpire2
329,1082635,Delhi,2017-05-06,2017,45,Delhi Daredevils,Mumbai Indians,Feroz Shah Kotla,Delhi Daredevils,field,False,Mumbai Indians,Runs,146.0,NaN,LMP Simmons,"['SV Samson', 'KK Nair', 'SS Iyer', 'RR Pant',...","['LMP Simmons', 'PA Patel', 'KA Pollard', 'RG ...",Nitin Menon,CK Nandan
388,980987,Bangalore,2016-05-14,2016,44,Royal Challengers Bangalore,Gujarat Lions,M Chinnaswamy Stadium,Gujarat Lions,field,False,Royal Challengers Bangalore,Runs,144.0,NaN,AB de Villiers,"['CH Gayle', 'V Kohli', 'AB de Villiers', 'SR ...","['DR Smith', 'BB McCullum', 'RA Jadeja', 'KD K...",AY Dandekar,VK Sharma
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,False,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen
453,829785,Bangalore,2015-05-06,2015,40,Royal Challengers Bangalore,Kings XI Punjab,M Chinnaswamy Stadium,Kings XI Punjab,field,False,Royal Challengers Bangalore,Runs,138.0,NaN,CH Gayle,"['CH Gayle', 'V Kohli', 'AB de Villiers', 'KD ...","['M Vijay', 'M Vohra', 'WP Saha', 'GJ Maxwell'...",RK Illingworth,VA Kulkarni
597,598027,Bangalore,2013-04-23,2013,31,Royal Challengers Bangalore,Pune Warriors,M Chinnaswamy Stadium,Pune Warriors,field,False,Royal Challengers Bangalore,Runs,130.0,NaN,CH Gayle,"['CH Gayle', 'TM Dilshan', 'V Kohli', 'AB de V...","['RV Uthappa', 'AJ Finch', 'Yuvraj Singh', 'LJ...",Aleem Dar,C Shamshuddin
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
608,598017,Bangalore,2013-04-16,2013,21,Royal Challengers Bangalore,Delhi Daredevils,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,True,Royal Challengers Bangalore,SuperOver,NaN,NaN,V Kohli,"['CH Gayle', 'KL Rahul', 'V Kohli', 'AB de Vil...","['DA Warner', 'V Sehwag', 'MC Juneja', 'DPMD J...",M Erasmus,VA Kulkarni
621,598004,Hyderabad,2013-04-07,2013,7,Sunrisers Hyderabad,Royal Challengers Bangalore,"Rajiv Gandhi International Stadium, Uppal",Royal Challengers Bangalore,bat,True,Sunrisers Hyderabad,SuperOver,NaN,NaN,GH Vihari,"['PA Reddy', 'PA Patel', 'CL White', 'GH Vihar...","['CH Gayle', 'TM Dilshan', 'V Kohli', 'KK Nair...",AK Chaudhary,S Ravi
708,501265,Delhi,2011-05-21,2011,68,Delhi Daredevils,Pune Warriors,Feroz Shah Kotla,Delhi Daredevils,bat,False,NaN,NoResults,NaN,NaN,NaN,"['NV Ojha', 'DA Warner', 'MS Wade', 'CA Ingram...","['MK Pandey', 'JP Faulkner', 'SC Ganguly', 'RV...",SS Hazare,RJ Tucker
819,419121,Chennai,2010-03-21,2009/10,16,Chennai Super Kings,Kings XI Punjab,"MA Chidambaram Stadium, Chepauk",Chennai Super Kings,field,True,Kings XI Punjab,SuperOver,NaN,NaN,J Theron,"['PA Patel', 'ML Hayden', 'SK Raina', 'M Vijay...","['RS Bopara', 'IK Pathan', 'KC Sangakkara', 'D...",K Hariharan,DJ Harper
883,392190,Cape Town,2009-04-23,2009,10,Kolkata Knight Riders,Rajasthan Royals,Newlands,Kolkata Knight Riders,field,True,Rajasthan Royals,SuperOver,NaN,NaN,YK Pathan,"['CH Gayle', 'BB McCullum', 'LR Shukla', 'BJ H...","['GC Smith', 'PC Valthaty', 'RJ Quiney', 'YK P...",MR Benson,M Erasmus