In [ ]:
import pandas as pd

In [ ]:
pd.__version__

'2.2.3'

In [ ]:
banking_data_csv = pd.read_csv('banking_data.csv')

In [ ]:
banking_data_csv

     customer_id   open_date account_type   balance  credit_score  job_sector
0     CUST_10000  2025-04-13     Checking  29519.13         648.0     Finance
1     CUST_10001  2025-06-29      Savings  37883.04           NaN     Finance
2     CUST_10002  2025-04-03     Checking      0.00         456.0     Unknown
3     CUST_10003  2025-01-15      Savings  19551.02         380.0        Tech
4     CUST_10004  2025-04-17      Savings  36719.00         507.0   Education
...          ...         ...          ...       ...           ...         ...
9995  CUST_19995  2025-06-24      Savings      0.00         313.0   Education
9996  CUST_19996  2025-06-21     Checking  29814.26         514.0     Unknown
9997  CUST_19997  2025-01-14  Credit Card  31841.05         835.0  Healthcare
9998  CUST_19998  2025-06-01      Savings   6800.01         319.0  Healthcare
9999  CUST_19999  2025-04-21  Credit Card   1998.78         787.0   Education

[10000 rows x 6 columns]

In [ ]:
banking_data_csv.columns

Index(['customer_id', 'open_date', 'account_type', 'balance', 'credit_score',
       'job_sector'],
      dtype='object')

In [ ]:
banking_data_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   customer_id   10000 non-null  object
 1   open_date     10000 non-null  object
 2   account_type  10000 non-null  object
 3   balance       10000 non-null  float64
 4   credit_score  9800 non-null   float64
 5   job_sector    9850 non-null   object
dtypes: float64(2), object(4)
memory usage: 468.9+ KB

In [ ]:
banking_data_csv.isna().sum().sum()

np.int64(350)

In [ ]:
banking_data_csv.describe()

            balance  credit_score
count  10000.000000   9800.000000
mean    8980.540894    576.039184
std    10497.071195    158.301336
min     -497.620000    300.000000
25%        0.000000    439.000000
50%     5210.215000    576.000000
75%    15460.420000    713.000000
max    62100.760000    849.000000

In [ ]:
banking_data_csv.head()

  customer_id   open_date account_type   balance  credit_score job_sector
0  CUST_10000  2025-04-13     Checking  29519.13         648.0    Finance
1  CUST_10001  2025-06-29      Savings  37883.04           NaN    Finance
2  CUST_10002  2025-04-03     Checking      0.00         456.0    Unknown
3  CUST_10003  2025-01-15      Savings  19551.02         380.0       Tech
4  CUST_10004  2025-04-17      Savings  36719.00         507.0  Education

In [ ]:
banking_data_csv_with_date = pd.read_csv('banking_data.csv',
                                        parse_dates=['open_date'])

In [ ]:
banking_data_csv_with_date.head()

  customer_id  open_date account_type   balance  credit_score job_sector
0  CUST_10000 2025-04-13     Checking  29519.13         648.0    Finance
1  CUST_10001 2025-06-29      Savings  37883.04           NaN    Finance
2  CUST_10002 2025-04-03     Checking      0.00         456.0    Unknown
3  CUST_10003 2025-01-15      Savings  19551.02         380.0       Tech
4  CUST_10004 2025-04-17      Savings  36719.00         507.0  Education

In [ ]:
banking_data_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   customer_id   10000 non-null  object
 1   open_date     10000 non-null  object
 2   account_type  10000 non-null  object
 3   balance       10000 non-null  float64
 4   credit_score  9800 non-null   float64
 5   job_sector    9850 non-null   object
dtypes: float64(2), object(4)
memory usage: 468.9+ KB

In [ ]:
banking_data_csv_with_date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   customer_id   10000 non-null  object
 1   open_date     10000 non-null  datetime64[ns]
 2   account_type  10000 non-null  object
 3   balance       10000 non-null  float64
 4   credit_score  9800 non-null   float64
 5   job_sector    9850 non-null   object
dtypes: datetime64[ns](1), float64(2), object(3)
memory usage: 468.9+ KB

In [ ]:
banking_data_csv_with_date['year'] =  banking_data_csv_with_date['open_date'].dt.year

In [ ]:
banking_data_csv_with_date.head()

  customer_id  open_date account_type   balance  credit_score job_sector  year
0  CUST_10000 2025-04-13     Checking  29519.13         648.0    Finance  2025
1  CUST_10001 2025-06-29      Savings  37883.04           NaN    Finance  2025
2  CUST_10002 2025-04-03     Checking      0.00         456.0    Unknown  2025
3  CUST_10003 2025-01-15      Savings  19551.02         380.0       Tech  2025
4  CUST_10004 2025-04-17      Savings  36719.00         507.0  Education  2025

In [ ]:
banking_data_csv_with_date.tail()

,customer_id,open_date,account_type,balance,credit_score,job_sector,year
9995,CUST_19995,2025-06-24,Savings,0.00,313.0,Education,2025
9996,CUST_19996,2025-06-21,Checking,29814.26,514.0,Unknown,2025
9997,CUST_19997,2025-01-14,Credit Card,31841.05,835.0,Healthcare,2025
9998,CUST_19998,2025-06-01,Savings,6800.01,319.0,Healthcare,2025
9999,CUST_19999,2025-04-21,Credit Card,1998.78,787.0,Education,2025

In [ ]:
banking_data_csv_3 = pd.read_csv('banking_data.csv',
                          na_values=['Unknown','NA','N/A','-'],
                                parse_dates=['open_date'])

In [ ]:
banking_data_csv_3.head()

  customer_id  open_date account_type   balance  credit_score job_sector
0  CUST_10000 2025-04-13     Checking  29519.13         648.0    Finance
1  CUST_10001 2025-06-29      Savings  37883.04           NaN    Finance
2  CUST_10002 2025-04-03     Checking      0.00         456.0        NaN
3  CUST_10003 2025-01-15      Savings  19551.02         380.0       Tech
4  CUST_10004 2025-04-17      Savings  36719.00         507.0  Education

In [ ]:
banking_data_csv_3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   customer_id   10000 non-null  object
 1   open_date     10000 non-null  datetime64[ns]
 2   account_type  10000 non-null  object
 3   balance       10000 non-null  float64
 4   credit_score  9800 non-null   float64
 5   job_sector    8520 non-null   object
dtypes: datetime64[ns](1), float64(2), object(3)
memory usage: 468.9+ KB

In [ ]:
banking_data_csv_with_date.head()

  customer_id  open_date account_type   balance  credit_score job_sector  year
0  CUST_10000 2025-04-13     Checking  29519.13         648.0    Finance  2025
1  CUST_10001 2025-06-29      Savings  37883.04           NaN    Finance  2025
2  CUST_10002 2025-04-03     Checking      0.00         456.0    Unknown  2025
3  CUST_10003 2025-01-15      Savings  19551.02         380.0       Tech  2025
4  CUST_10004 2025-04-17      Savings  36719.00         507.0  Education  2025

In [ ]:
banking_data_csv_with_date[(banking_data_csv_with_date['job_sector'] == 'Tech')
& (banking_data_csv_with_date['account_type'] == 'Checking')]

,customer_id,open_date,account_type,balance,credit_score,job_sector,year
6,CUST_10006,2025-01-21,Checking,15759.85,746.0,Tech,2025
12,CUST_10012,2025-04-10,Checking,3719.38,841.0,Tech,2025
44,CUST_10044,2025-05-12,Checking,0.00,748.0,Tech,2025
97,CUST_10097,2025-03-22,Checking,0.00,710.0,Tech,2025
151,CUST_10151,2025-03-03,Checking,14717.07,341.0,Tech,2025
...,...,...,...,...,...,...,...
9901,CUST_19901,2025-04-23,Checking,0.00,593.0,Tech,2025
9927,CUST_19927,2025-01-13,Checking,0.00,396.0,Tech,2025
9974,CUST_19974,2025-01-01,Checking,0.00,685.0,Tech,2025
9976,CUST_19976,2025-03-13,Checking,18245.54,470.0,Tech,2025
9980,CUST_19980,2025-05-27,Checking,7336.65,467.0,Tech,2025

In [ ]:
cnd1 = (banking_data_csv_with_date['job_sector'] == 'Tech')
cnd2 = (banking_data_csv_with_date['account_type'] == 'Checking')

In [ ]:
banking_data_csv_with_date[cnd1 | cnd2]

,customer_id,open_date,account_type,balance,credit_score,job_sector,year
0,CUST_10000,2025-04-13,Checking,29519.13,648.0,Finance,2025
2,CUST_10002,2025-04-03,Checking,0.00,456.0,Unknown,2025
3,CUST_10003,2025-01-15,Savings,19551.02,380.0,Tech,2025
5,CUST_10005,2025-03-13,Savings,19941.84,385.0,Tech,2025
6,CUST_10006,2025-01-21,Checking,15759.85,746.0,Tech,2025
...,...,...,...,...,...,...,...
9989,CUST_19989,2025-01-14,Checking,0.00,449.0,Finance,2025
9990,CUST_19990,2025-01-01,Savings,23385.85,655.0,Tech,2025
9991,CUST_19991,2025-03-31,Checking,5379.16,832.0,Education,2025
9992,CUST_19992,2025-03-30,Investment,0.00,672.0,Tech,2025
9996,CUST_19996,2025-06-21,Checking,29814.26,514.0,Unknown,2025

In [ ]:
banking_data_csv_with_date[~cnd1]

,customer_id,open_date,account_type,balance,credit_score,job_sector,year
0,CUST_10000,2025-04-13,Checking,29519.13,648.0,Finance,2025
1,CUST_10001,2025-06-29,Savings,37883.04,NaN,Finance,2025
2,CUST_10002,2025-04-03,Checking,0.00,456.0,Unknown,2025
4,CUST_10004,2025-04-17,Savings,36719.00,507.0,Education,2025
7,CUST_10007,2025-04-13,Checking,0.00,476.0,Finance,2025
...,...,...,...,...,...,...,...
9995,CUST_19995,2025-06-24,Savings,0.00,313.0,Education,2025
9996,CUST_19996,2025-06-21,Checking,29814.26,514.0,Unknown,2025
9997,CUST_19997,2025-01-14,Credit Card,31841.05,835.0,Healthcare,2025
9998,CUST_19998,2025-06-01,Savings,6800.01,319.0,Healthcare,2025
9999,CUST_19999,2025-04-21,Credit Card,1998.78,787.0,Education,2025

In [ ]:
grouped_df = banking_data_csv_with_date.groupby("job_sector").agg(
    total_balance=("balance","sum"),
    mean_balance = ("balance","mean"),
    median_balance=("balance","median"),
    no_of_user=("customer_id","count")
)

In [ ]:
grouped_df

            total_balance  mean_balance  median_balance  no_of_user
job_sector
Education     12401988.62   8606.515350        4922.830        1441
Finance       13650369.75   9905.928701        6247.660        1378
Healthcare    13014750.94   8938.702569        5639.670        1456
Retail        12515930.26   9023.742076        5490.990        1387
Tech          12821659.29   8928.732096        4952.950        1436
Unemployed    12293573.78   8645.269887        4813.365        1422
Unknown       11915670.10   8959.150451        5095.140        1330

In [ ]:
grouped_df['total_balance']

job_sector
Education     12401988.62
Finance       13650369.75
Healthcare    13014750.94
Retail        12515930.26
Tech          12821659.29
Unemployed    12293573.78
Unknown       11915670.10
Name: total_balance, dtype: float64

In [ ]:
gdf_2 = grouped_df.reset_index()

In [ ]:
grouped_df.to_csv('grouped_result.csv')

In [ ]:
type(grouped_df)

pandas.core.frame.DataFrame

In [ ]:
gdf_2

   job_sector  total_balance  mean_balance  median_balance  no_of_user
0   Education    12401988.62   8606.515350        4922.830        1441
1     Finance    13650369.75   9905.928701        6247.660        1378
2  Healthcare    13014750.94   8938.702569        5639.670        1456
3      Retail    12515930.26   9023.742076        5490.990        1387
4        Tech    12821659.29   8928.732096        4952.950        1436
5  Unemployed    12293573.78   8645.269887        4813.365        1422
6     Unknown    11915670.10   8959.150451        5095.140        1330

In [ ]:
gdf_2['job_sector']

0     Education
1       Finance
2    Healthcare
3        Retail
4          Tech
5    Unemployed
6       Unknown
Name: job_sector, dtype: object